dist:
  name: otelcol-raki
  description: Raki's OTel Collector distribution for learning stuff
  output_path: ./opentelemetry-collector-raki/otelcol-raki

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.117.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.117.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.117.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.117.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.117.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.117.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0