extensions:
  zpages:
    endpoint: localhost:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  tailtracer:
    secret_attribute_name: secret.attr
    secret_attribute_length: 5
    interval: 5s
    number_of_traces: 1

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

connectors:
  exampleconnector:
    attribute_name: secret.attr

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: localhost:14317
    tls:
      insecure: true
  emptyexporter:
    should_log: true

service:
  pipelines:
    traces:
      receivers: [otlp, tailtracer]
      processors: [memory_limiter, batch]
      exporters: [debug, otlp/jaeger, exampleconnector, emptyexporter]
    metrics:
      receivers: [otlp, exampleconnector]
      processors: [memory_limiter, batch]
      exporters: [debug, emptyexporter]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, emptyexporter]

  extensions: [zpages]
